apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-webapi
  template:
    metadata:
      labels:
        app: dotnet-webapi
    spec:
      containers:
        - name: dotnet-webapi
          image: dotnet-webapi:v1
          # Pull from local docker images already available from build
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbConfig__Host
              value: mongodb-service
            - name: MongoDbConfig__Password
              valueFrom:
                secretKeyRef:
                  name: dotnet-webapi-secrets
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapi-service
spec:
  type: LoadBalancer
  selector:
    # Use the same app label used for selector match labels in deployment
    app: dotnet-webapi
  ports:
    # Port open to the outside mapping to port in the container
    - port: 80
      # Port specified for the container e.g. deployments port/containerPort
      targetPort: 80
