# REF: https://kubernetes.io/blog/2017/01/running-mongodb-on-kubernetes-with-statefulsets/
# Manages stateful applications providing guarantees about the ordering and uniqueness of pods
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          # Pull from local docker images already available from build
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dotnet-webapi-secrets
                  key: mongodb-password
          volumeMounts:
            - name: mongodbdata
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodbdata
      spec:
        # Volume mounted as read/write by a single node
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  # Turns into headless service
  clusterIP: None
  selector:
    # Use same app name in pod template
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
